spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:nlp
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8085